baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Pherde's notes"

theme = 'archie'

[params]
mode="toggle"
customcss = ["css/first.css"]
subtitle = 'Notes from an old dev trying to learn new things!'

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/pherde"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/pherde"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://linkedin.com/pherde"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
