baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Pherde's notes"

theme = 'archie'

[params]
mode="toggle"
favicon="https://upload.wikimedia.org/wikipedia/commons/1/1f/Bash_Logo_Favicon_Colored.svg"
customcss = ["css/first.css"]
subtitle = 'Just some notes from another dev trying to learn new things!'

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/pherde"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://cwb.social/@fernando"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/fernando-eckhardt-valle/"

[[params.social]]
name = "Mail"
icon = "mail"
url = "phervalle@proton.me"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
